"""Documented exceptions to the cdk-nag security rule packs.

WHAT IS cdk-nag?
----------------
``cdk-nag`` reads the CloudFormation template that CDK produces and checks it
against published AWS best-practice rules (the "AwsSolutions" pack used in AWS
Solutions reviews). Findings are raised as synth-time errors, so an insecure
template cannot be deployed by accident.

WHY SUPPRESSIONS EXIST
----------------------
Some findings are genuinely not applicable, and some are conscious trade-offs
for a demo/dev environment. The professional way to handle those is *not* to
turn the scanner off, but to suppress each finding individually with a written
reason. The suppression list then becomes an auditable record of "we saw this,
here is why we accepted it" — and anything new shows up loudly.

Run the scan with:  cdk synth -c nag=true
"""

import contextlib

from aws_cdk import Stack
from cdk_nag import NagSuppressions


def apply_nag_suppressions(stack: Stack) -> None:
    """Attach justified suppressions to ``stack``.

    Suppressions are applied with ``apply_to_children=True`` at the stack level
    for findings that are inherent to CDK's own helper resources, and at
    specific construct paths for the deliberate architectural choices.
    """
    # ------------------------------------------------------------------
    # A. Findings inside CDK-generated helper resources
    # ------------------------------------------------------------------
    # CDK creates small Lambda-backed custom resources (log retention setter,
    # bucket auto-delete, default-SG restriction, ECS instance drain hook). We
    # do not author their IAM policies or runtimes, and AWS maintains them.
    NagSuppressions.add_stack_suppressions(
        stack,
        [
            {
                "id": "AwsSolutions-IAM4",
                "reason": (
                    "AWS-managed policies are used deliberately in two places: "
                    "(1) CDK's own custom-resource Lambdas, whose policies we do "
                    "not author, and (2) the EC2 instance role, where "
                    "AmazonEC2ContainerServiceforEC2Role, AmazonSSMManagedInstanceCore "
                    "and CloudWatchAgentServerPolicy are the AWS-authored minimum "
                    "for an ECS container instance. Hand-rolling them would drift "
                    "out of date as ECS adds APIs."
                ),
            },
            {
                "id": "AwsSolutions-IAM5",
                "reason": (
                    "Remaining wildcards are unavoidable: S3 object-level grants "
                    "need <bucket>/* to cover the objects inside the bucket, and "
                    "cloudwatch:PutMetricData has no ARN to scope to (it is "
                    "instead restricted with a cloudwatch:namespace condition). "
                    "CDK's custom-resource policies are also covered here."
                ),
            },
            {
                "id": "AwsSolutions-L1",
                "reason": (
                    "The Lambda runtime versions belong to CDK-generated custom "
                    "resources and are upgraded by upgrading aws-cdk-lib, not by "
                    "application code."
                ),
            },
            {
                "id": "AwsSolutions-SNS3",
                "reason": (
                    "Applies to the SNS topic that CDK creates for the ECS "
                    "instance-draining lifecycle hook. Its only publisher is the "
                    "EC2 Auto Scaling service over AWS-internal networking, and "
                    "the topic's policy is generated by CDK. The topic this stack "
                    "does own (OpsNotifications) sets enforce_ssl=True."
                ),
            },
            {
                "id": "CdkNagValidationFailure",
                "reason": (
                    "Raised on the security groups CDK generates for VPC "
                    "interface endpoints. Their ingress rule references the VPC "
                    "CIDR as a CloudFormation intrinsic (Fn::GetAtt), which "
                    "cdk-nag cannot evaluate at synth time. The rule is correct "
                    "by construction: it admits only traffic originating inside "
                    "this VPC."
                ),
            },
            {
                "id": "AwsSolutions-ECS2",
                "reason": (
                    "The container's environment variables carry no secrets: "
                    "they are the assets bucket name, the region, the environment "
                    "name and a pre-signed URL TTL. Database credentials are NOT "
                    "passed this way — the application reads them from Secrets "
                    "Manager at runtime using its task role."
                ),
            },
        ],
    )

    # ------------------------------------------------------------------
    # B. Deliberate architectural decisions
    # ------------------------------------------------------------------
    _suppress(
        stack,
        "/Storage/AccessLogsBucket/Resource",
        [
            {
                "id": "AwsSolutions-S1",
                "reason": (
                    "This *is* the access-log bucket. Enabling server access "
                    "logging on it would log its own log writes, producing an "
                    "endless feedback loop and unbounded storage growth."
                ),
            },
            {
                "id": "AwsSolutions-S10",
                "reason": (
                    "enforce_ssl=True is set, which adds the aws:SecureTransport "
                    "deny policy the rule looks for; the finding is raised on the "
                    "bucket resource before the policy is evaluated."
                ),
            },
        ],
    )

    _suppress(
        stack,
        "/Compute/AlbSecurityGroup/Resource",
        [
            {
                "id": "AwsSolutions-EC23",
                "reason": (
                    "This is an internet-facing web application, so 0.0.0.0/0 on "
                    "ports 80 and 443 is the intended design. No other port is "
                    "open, and the container hosts behind it only accept traffic "
                    "from this security group."
                ),
            }
        ],
    )

    _suppress(
        stack,
        "/Compute/LoadBalancer/Resource",
        [
            {
                "id": "AwsSolutions-ELB2",
                "reason": "Access logging is enabled via log_access_logs() to the dedicated log bucket.",
            },
            {
                "id": "AwsSolutions-ELB5",
                "reason": (
                    "Only relevant when no ACM certificate is supplied. Deploy "
                    "with -c certificate_arn=<arn> and the stack serves HTTPS on "
                    "443 and 301-redirects port 80 to it."
                ),
            },
        ],
    )

    _suppress(
        stack,
        "/Data/Database/Resource",
        [
            {
                "id": "AwsSolutions-RDS3",
                "reason": (
                    "Multi-AZ is configuration-driven (db_multi_az) and is "
                    "enabled for production. Dev runs single-AZ to control cost."
                ),
            },
            {
                "id": "AwsSolutions-RDS10",
                "reason": (
                    "Deletion protection is configuration-driven "
                    "(retain_data_on_delete) and enabled for production; dev "
                    "environments must stay disposable."
                ),
            },
            {
                "id": "AwsSolutions-RDS11",
                "reason": (
                    "The default PostgreSQL port is kept intentionally. Port "
                    "obscurity adds no real protection here because the instance "
                    "lives in isolated subnets and its security group admits only "
                    "the ECS host security group."
                ),
            },
        ],
    )


def _suppress(stack: Stack, relative_path: str, suppressions: list) -> None:
    """Apply suppressions to a construct path, ignoring paths that do not exist.

    Some resources are conditional (for example the database), so a hard-coded
    path may legitimately be absent. Tolerating that keeps the scan usable in
    every configuration instead of crashing on the smallest one.
    """
    with contextlib.suppress(Exception):
        NagSuppressions.add_resource_suppressions_by_path(
            stack, f"/{stack.stack_name}{relative_path}", suppressions
        )
