"""Database layer (bonus requirement): a managed PostgreSQL instance on RDS.

WHAT MAKES THIS "SECURE BY DEFAULT"
-----------------------------------
  * It sits in **isolated** subnets — no route to or from the internet at all.
  * Its security group accepts connections from exactly one source: the
    security group of the ECS container hosts. Nothing else in the VPC can even
    open a TCP connection to it.
  * The password is generated by AWS, stored in **Secrets Manager**, and never
    appears in the CDK source, the CloudFormation template or the console.
  * Storage is encrypted at rest, and ``rds.force_ssl`` makes the server refuse
    unencrypted client connections, so data is encrypted in transit too.
  * Automated backups and (in production) a standby in a second AZ.
"""

from aws_cdk import (
    Duration,
    RemovalPolicy,
    aws_ec2 as ec2,
    aws_iam as iam,
    aws_rds as rds,
    aws_secretsmanager as secretsmanager,
)
from constructs import Construct

from ..config import EnvironmentConfig
from .network import Network, to_retention_days

POSTGRES_PORT = 5432


class Database(Construct):
    """A single-instance PostgreSQL database with a private endpoint.

    Attributes:
        instance: the RDS database instance.
        secret: the Secrets Manager secret holding host, port, username and
            password. Applications should read this at start-up rather than
            taking credentials from environment variables.
        security_group: the database's firewall.
    """

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        config: EnvironmentConfig,
        network: Network,
        client_security_group: ec2.ISecurityGroup,
        client_role: iam.IRole,
    ) -> None:
        super().__init__(scope, construct_id)
        self._config = config

        vpc = network.vpc

        # ------------------------------------------------------------------
        # 1. Firewall: exactly one way in
        # ------------------------------------------------------------------
        self.security_group = ec2.SecurityGroup(
            self,
            "DatabaseSecurityGroup",
            vpc=vpc,
            security_group_name=config.resource_name("db-sg"),
            description="PostgreSQL: reachable only from the ECS container hosts",
            # A database never needs to initiate outbound connections. Turning
            # egress off entirely limits what an attacker could do from inside
            # the instance if they ever got there.
            allow_all_outbound=False,
        )
        self.security_group.add_ingress_rule(
            # Referencing the *client security group* rather than a CIDR range
            # means this rule keeps working as hosts are replaced and IPs
            # change, and it never accidentally covers an unrelated resource.
            peer=client_security_group,
            connection=ec2.Port.tcp(POSTGRES_PORT),
            description="PostgreSQL from the ECS container hosts",
        )

        # ------------------------------------------------------------------
        # 2. Subnet group: which subnets the instance may live in
        # ------------------------------------------------------------------
        subnet_group = rds.SubnetGroup(
            self,
            "DatabaseSubnetGroup",
            description="Isolated subnets for the application database",
            vpc=vpc,
            # PRIVATE_ISOLATED subnets have no NAT route, so there is no path
            # to the internet in either direction.
            vpc_subnets=network.isolated_subnets,
            removal_policy=RemovalPolicy.DESTROY,  # the group itself holds no data
        )

        # ------------------------------------------------------------------
        # 3. Credentials, generated and stored by AWS
        # ------------------------------------------------------------------
        # from_generated_secret creates a random password in Secrets Manager.
        # Nothing sensitive is ever written into source control, and the app
        # fetches the value at runtime.
        credentials = rds.Credentials.from_generated_secret(
            username="appadmin",
            secret_name=config.resource_name("db-credentials"),
            # PostgreSQL disallows these characters in passwords / connection
            # strings, so exclude them to avoid puzzling auth failures.
            exclude_characters=" %+~`#$&*()|[]{}:;<>?!'/@\"\\",
        )

        # ------------------------------------------------------------------
        # 4. Parameter group: enforce TLS on the server side
        # ------------------------------------------------------------------
        parameter_group = rds.ParameterGroup(
            self,
            "DatabaseParameters",
            engine=self._engine(),
            description="Force TLS and log slow queries",
            parameters={
                # The important one: PostgreSQL will refuse any client that
                # tries to connect without TLS. Encryption in transit becomes
                # a server-enforced guarantee, not a client-side hope.
                "rds.force_ssl": "1",
                # Log statements slower than 1 second. Cheap, and it is usually
                # the first thing you want when investigating latency.
                "log_min_duration_statement": "1000",
                "log_connections": "1",
                "log_disconnections": "1",
            },
        )

        # ------------------------------------------------------------------
        # 5. The instance itself
        # ------------------------------------------------------------------
        self.instance = rds.DatabaseInstance(
            self,
            "Database",
            instance_identifier=config.resource_name("db"),
            engine=self._engine(),
            instance_type=ec2.InstanceType(config.db_instance_type),
            vpc=vpc,
            subnet_group=subnet_group,
            security_groups=[self.security_group],
            credentials=credentials,
            parameter_group=parameter_group,
            port=POSTGRES_PORT,
            # --- Storage ---------------------------------------------------
            allocated_storage=20,
            # Storage autoscaling: RDS grows the volume automatically before it
            # fills up. Running out of disk on a database is an outage, and this
            # single line prevents the most common cause of one.
            max_allocated_storage=100,
            storage_type=rds.StorageType.GP3,
            # Encryption at rest with the AWS-managed RDS key. (Set
            # storage_encryption_key=<your KMS key> if you need your own key
            # with its own rotation and audit trail.)
            storage_encrypted=True,
            # --- Availability ----------------------------------------------
            # multi_az=True keeps a synchronous standby in a second AZ and
            # fails over automatically. Roughly doubles the cost, so it is
            # production-only here.
            multi_az=config.db_multi_az,
            # --- Backup and recovery ---------------------------------------
            backup_retention=Duration.days(7 if config.is_production else 1),
            # Times are UTC and deliberately outside business hours.
            preferred_backup_window="03:00-04:00",
            preferred_maintenance_window="Sun:04:30-Sun:05:30",
            copy_tags_to_snapshot=True,
            delete_automated_backups=not config.retain_data_on_delete,
            # --- Patching --------------------------------------------------
            # Let AWS apply minor-version security patches during the
            # maintenance window above.
            auto_minor_version_upgrade=True,
            # --- Access ----------------------------------------------------
            # IAM database authentication lets the application log in with its
            # IAM role and a short-lived token instead of a long-lived
            # password. The password stays as a break-glass fallback.
            iam_authentication=True,
            publicly_accessible=False,  # belt and braces; isolated subnets already prevent it
            # --- Observability ---------------------------------------------
            cloudwatch_logs_exports=["postgresql", "upgrade"],
            cloudwatch_logs_retention=to_retention_days(config.log_retention_days),
            # Performance Insights is not offered on the smallest instance
            # classes, so it is behind a config flag rather than always on.
            enable_performance_insights=config.db_performance_insights,
            monitoring_interval=(
                Duration.seconds(60) if config.is_production else None
            ),
            # --- Lifecycle -------------------------------------------------
            # Two independent guards on production data:
            #   deletion_protection -> RDS itself refuses a delete API call.
            #   removal_policy       -> what CloudFormation does on stack delete.
            #                           SNAPSHOT means "take a final backup first".
            deletion_protection=config.retain_data_on_delete,
            removal_policy=(
                RemovalPolicy.SNAPSHOT
                if config.retain_data_on_delete
                else RemovalPolicy.DESTROY
            ),
        )

        # The secret is created as part of the instance; expose it for outputs.
        self.secret: secretsmanager.ISecret = self.instance.secret  # type: ignore[assignment]

        # ------------------------------------------------------------------
        # 5b. Automatic password rotation
        # ------------------------------------------------------------------
        # A password that never changes is a password that eventually leaks.
        # Secrets Manager runs an AWS-supplied Lambda that generates a new
        # password, applies it to the database and updates the secret — all
        # without a deployment or downtime, because the application reads the
        # secret at connection time.
        if self.secret is not None:
            self.instance.add_rotation_single_user(
                automatically_after=Duration.days(30),
                # The rotation Lambda must reach the Secrets Manager *API*, so it
                # goes in the private subnets (which have a NAT route), not the
                # isolated ones. It reaches the database over the VPC; CDK adds
                # the required security group rule automatically.
                vpc_subnets=network.private_subnets,
                exclude_characters=" %+~`#$&*()|[]{}:;<>?!'/@\"\\",
                # Do not rotate during the deployment itself. Rotating on every
                # `cdk deploy` would turn a small template change into a
                # credential change, and a failure there fails the whole deploy.
                rotate_immediately_on_update=False,
            )

        # ------------------------------------------------------------------
        # 6. Let the application read its own credentials — and only those
        # ------------------------------------------------------------------
        if self.secret is not None:
            self.secret.grant_read(client_role)
        # Permission to request a short-lived IAM auth token for one specific
        # database user. Scoped to the resource, so the role cannot mint tokens
        # for any other user or database.
        self.instance.grant_connect(client_role, db_user="appadmin")

    # ---------------------------------------------------------------------- #
    # Helpers                                                                #
    # ---------------------------------------------------------------------- #
    @staticmethod
    def _engine() -> rds.IInstanceEngine:
        """Pin the engine version explicitly.

        Pinning matters: if you let AWS choose the default, a redeploy months
        later can silently target a different major version. Bump this
        deliberately, after testing.
        """
        return rds.DatabaseInstanceEngine.postgres(
            version=rds.PostgresEngineVersion.VER_17_6
        )

    @property
    def endpoint_address(self) -> str:
        """Private DNS name clients should connect to."""
        return self.instance.db_instance_endpoint_address

    @property
    def endpoint_port(self) -> str:
        """Port as a string (CloudFormation outputs must be strings)."""
        return self.instance.db_instance_endpoint_port
